# Generated by Django 4.1.2 on 2022-12-13 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, verbose_name='Country')),
                ('region', models.CharField(blank=True, max_length=150, verbose_name='Region')),
                ('state', models.CharField(blank=True, max_length=150, verbose_name='State')),
                ('street', models.CharField(blank=True, max_length=150, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, max_length=150, verbose_name='House Number')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='cities.city')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
