# Generated by Django 4.1.2 on 2022-12-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='House Number'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Street'),
        ),
    ]
