# Generated by Django 4.1.2 on 2023-05-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_fieldphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
