# Generated by Django 4.1.2 on 2023-07-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_field_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='timezone',
            field=models.IntegerField(default=0, verbose_name='Time Zone Difference'),
        ),
    ]
