# Generated by Django 4.1.2 on 2022-12-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Муж.', 'Муж.'), ('Жен.', 'Жен.')], default='Муж.', max_length=50, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.FloatField(default=0, verbose_name='Rank'),
        ),
    ]
