# Generated by Django 4.1.2 on 2023-01-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_duration_options'),
        ('users', '0013_user_favorite_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_events',
            field=models.ManyToManyField(blank=True, related_name='in_favorites', to='events.event'),
        ),
    ]
