# Generated by Django 4.1.2 on 2023-01-24 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_favorite_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
        migrations.CreateModel(
            name='RankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.FloatField(default=5, verbose_name='Rank')),
                ('create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Create')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rank History',
                'verbose_name_plural': 'Ranks History',
                'ordering': ['create'],
            },
        ),
    ]
