# Generated by Django 4.1.2 on 2023-01-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_involvement_user_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='involvement',
            field=models.PositiveIntegerField(default=1, verbose_name='Involvement'),
        ),
    ]
