# Generated by Django 4.1.2 on 2023-02-07 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_involvement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_players',
            field=models.ManyToManyField(blank=True, related_name='in_favorite_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
