# Generated by Django 4.1.2 on 2023-02-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_favorite_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='acronym',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Acronym'),
        ),
    ]
