# Generated by Django 4.1.2 on 2023-02-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_format_rate'),
        ('users', '0019_position_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankhistory',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranks_history', to='events.event'),
        ),
    ]
