# Generated by Django 4.1.2 on 2023-04-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_is_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Парень', 'Парень'), ('Девушка', 'Девушка')], default='Парень', max_length=50, verbose_name='Gender'),
        ),
    ]
