# Generated by Django 4.1.2 on 2023-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Apple Id'),
        ),
    ]
