# Generated by Django 4.1.2 on 2023-05-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_apple_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
