# Generated by Django 4.1.2 on 2023-05-24 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_remove_event_organizer_event_organizers'),
        ('users', '0027_remove_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rivals',
        ),
        migrations.CreateModel(
            name='UserRivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rivals', to='events.event')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rivals_from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rivals_to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Rivals',
                'verbose_name_plural': 'User Rivals',
            },
        ),
    ]
