# Generated by Django 4.1.2 on 2023-05-24 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_user_rivals_userrivals'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rivals',
            field=models.ManyToManyField(blank=True, related_name='in_rivals', through='users.UserRivals', to=settings.AUTH_USER_MODEL),
        ),
    ]
