# Generated by Django 4.1.2 on 2023-06-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_rankhistory_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True, verbose_name='Is First Login'),
        ),
    ]
