# Generated by Django 4.1.2 on 2023-06-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_user_big_card_photo_user_overlay_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='big_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Big Card Photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='overlay_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Overlay Photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='small_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Small Card Photo'),
        ),
    ]
