# Generated by Django 4.1.2 on 2023-07-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankhistory',
            name='reason',
            field=models.CharField(blank=True, choices=[('Join To Event', 'Join To Event'), ('Leave Event', 'Leave Event'), ('Create Event', 'Create Event'), ('Cancel Event', 'Cancel Event')], default=None, max_length=50, null=True, verbose_name='Reason Of Creation Rank'),
        ),
    ]
