# Generated by Django 4.1.2 on 2022-12-12 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_event_geo_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEventAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='Action Time')),
                ('action', models.CharField(choices=[('Join To Event', 'Join To Event'), ('Leave Event', 'Leave Event'), ('Create Event', 'Create Event'), ('Cancel Event', 'Cancel Event')], default='Join To Event', max_length=50, verbose_name='Action Name')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_events_actions', to='events.event')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_events_actions', to='events.cancelreasons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_events_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Event Action',
                'verbose_name_plural': 'User Event Actions',
            },
        ),
    ]
