# Generated by Django 4.1.2 on 2023-07-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_usernotice_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('Warning', 'Warning'), ('Critical', 'Critical'), ('New Player', 'New Player'), ('Invite', 'Invite'), ('Complete Players', 'Complete Players'), ('Cancel Event', 'Cancel Event'), ('Join', 'Join'), ('Regard', 'Regard'), ('Leave', 'Leave')], default='Warning', max_length=150, verbose_name='Notice Type'),
        ),
    ]
