# Generated by Django 4.1.2 on 2022-12-19 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_address'),
        ('chats', '0002_remove_message_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='events.event'),
        ),
    ]
