# Generated by Django 4.1.2 on 2022-11-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notice',
            field=models.TextField(blank=True, verbose_name='Notices'),
        ),
    ]
