# Generated by Django 4.1.2 on 2022-11-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_player',
            field=models.BooleanField(default=False, verbose_name='Is Organizer Play'),
        ),
    ]
