# Generated by Django 4.1.2 on 2022-11-29 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_event_organizer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'event')},
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player', to='events.team')),
            ],
            options={
                'verbose_name': 'Team Player',
                'verbose_name_plural': 'Teams Players',
                'unique_together': {('player', 'team')},
            },
        ),
        migrations.CreateModel(
            name='EventPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_player', to='events.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Player',
                'verbose_name_plural': 'Events Players',
                'unique_together': {('player', 'event')},
            },
        ),
    ]
