# Generated by Django 4.1.2 on 2022-12-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_team_unique_together_teamplayer_eventplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('Step 1', 'Step 1'), ('Step 2', 'Step 2'), ('Step 3', 'Step 3')], default='Step 1', max_length=50, verbose_name='Step Name')),
                ('complete', models.BooleanField(default=False, verbose_name='Step Is Complete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_step', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Step',
                'verbose_name_plural': 'Events Steps',
                'unique_together': {('step', 'event')},
            },
        ),
    ]
