# Generated by Django 4.1.2 on 2022-12-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountCircles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Label')),
                ('count', models.IntegerField(verbose_name='Count Of Circles')),
            ],
            options={
                'verbose_name': 'Count Circles',
                'verbose_name_plural': 'Count Circles',
            },
        ),
        migrations.CreateModel(
            name='DistributionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Method')),
            ],
            options={
                'verbose_name': 'Distribution Method',
                'verbose_name_plural': 'Distribution Methods',
            },
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Label')),
                ('duration', models.IntegerField(verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Duration',
                'verbose_name_plural': 'Durations',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Label')),
                ('count', models.IntegerField(verbose_name='Count In Team')),
            ],
            options={
                'verbose_name': 'Format',
                'verbose_name_plural': 'Formats',
            },
        ),
        migrations.AlterField(
            model_name='cancelreasons',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='event',
            name='count_circles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='events.countcircles'),
        ),
        migrations.AddField(
            model_name='event',
            name='distribution_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='events.distributionmethod'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='events.duration'),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='events.format'),
        ),
    ]
