# Generated by Django 4.1.2 on 2022-12-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_scorer_event_until_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Label'),
        ),
    ]
