# Generated by Django 4.1.2 on 2022-12-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_format_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countcircles',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='duration',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Label'),
        ),
    ]
