# Generated by Django 4.1.2 on 2022-12-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_until_goal_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstep',
            options={'ordering': ['id'], 'verbose_name': 'Event Step', 'verbose_name_plural': 'Events Steps'},
        ),
    ]
