# Generated by Django 4.1.2 on 2022-12-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_geo_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
    ]
