# Generated by Django 4.1.2 on 2022-12-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_address'),
        ('events', '0016_remove_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='cities.address'),
        ),
    ]
