# Generated by Django 4.1.2 on 2022-12-19 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0017_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Team Number'),
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='events.event'),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='events.team'),
        ),
    ]
