# Generated by Django 4.1.2 on 2022-12-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_team_number_alter_team_event_alter_teamplayer_player_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1', models.IntegerField(default=0, verbose_name='Score 1 Team')),
                ('score_2', models.IntegerField(default=0, verbose_name='Score 2 Team')),
                ('time_begin', models.TimeField(blank=True, null=True, verbose_name='Time Begin')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Time End')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_games', to='events.event')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='even_games_teams_1', to='events.team')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='even_games_teams_2', to='events.team')),
            ],
            options={
                'verbose_name': 'Event Game',
                'verbose_name_plural': 'Event Games',
                'unique_together': {('event', 'team_1', 'team_2')},
            },
        ),
    ]
