# Generated by Django 4.1.2 on 2022-12-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_eventgame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgame',
            options={'ordering': ['number'], 'verbose_name': 'Event Game', 'verbose_name_plural': 'Event Games'},
        ),
        migrations.AddField(
            model_name='eventgame',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Number'),
        ),
    ]
