# Generated by Django 4.1.2 on 2022-12-21 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_eventgame_options_eventgame_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgame',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_games_teams_1', to='events.team'),
        ),
        migrations.AlterField(
            model_name='eventgame',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_games_teams_2', to='events.team'),
        ),
    ]
