# Generated by Django 4.1.2 on 2022-12-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_format_label_event_is_paid_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(default='RUB', max_length=50, verbose_name='Currency'),
        ),
    ]
