# Generated by Django 4.1.2 on 2023-01-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_goal_gameperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgame',
            name='score_1',
        ),
        migrations.RemoveField(
            model_name='eventgame',
            name='score_2',
        ),
    ]
