# Generated by Django 4.1.2 on 2023-01-23 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_duration_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventgame',
            unique_together=set(),
        ),
    ]
