# Generated by Django 4.1.2 on 2023-01-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_eventgame_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='rate',
            field=models.FloatField(default=1, verbose_name='Rate For Rank'),
        ),
    ]
