# Generated by Django 4.1.2 on 2023-02-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_format_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'time_begin'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventplayer',
            options={'ordering': ['event__date', 'event__time_begin'], 'verbose_name': 'Event Player', 'verbose_name_plural': 'Events Players'},
        ),
    ]
