# Generated by Django 4.1.2 on 2023-04-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_fieldphoto'),
        ('events', '0031_alter_event_options_alter_eventplayer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cities.field'),
        ),
    ]
