# Generated by Django 4.1.2 on 2023-05-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_event_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='geo_point',
        ),
    ]
