# Generated by Django 4.1.2 on 2023-06-09 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0035_color_playernumber_alter_teamplayer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='auto',
            field=models.BooleanField(default=False, verbose_name='Is Auto Goal'),
        ),
    ]
