# Generated by Django 4.1.2 on 2023-06-14 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_announce'),
        ('events', '0037_event_duration_opt_event_genders_event_is_news_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='announce',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='telegram.announce'),
        ),
    ]
