# Generated by Django 4.1.2 on 2023-06-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_event_announce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
    ]
