# Generated by Django 4.1.2 on 2023-06-14 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram', '0002_alter_telegramchannel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramchannel',
            name='admin',
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='telegram_channels_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='channel_id',
            field=models.CharField(default=0, max_length=150, unique=True, verbose_name='Channel Id'),
            preserve_default=False,
        ),
    ]
