# Generated by Django 4.1.2 on 2023-06-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_remove_telegramchannel_admin_telegramchannel_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='has_bot',
            field=models.BooleanField(default=False, verbose_name='Channel Has Bot'),
        ),
    ]
