# Generated by Django 4.1.2 on 2023-06-14 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_telegramchannel_has_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=50, verbose_name='Message Id')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announces', to='telegram.telegramchannel')),
            ],
            options={
                'verbose_name': 'Announce',
                'verbose_name_plural': 'Announces',
                'unique_together': {('message_id', 'channel')},
            },
        ),
    ]
